#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import json
import math
import random
import subprocess
import time
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import List


@dataclass
class TrialResult:
    trial: int
    rows: int
    status: str
    elapsed_sec: float
    return_code: int | None
    timed_out: bool


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Auto-tune LSTM training sample size under a per-run timeout budget"
    )
    parser.add_argument(
        "--full-train-csv",
        type=Path,
        default=Path("datasets/LSTM/processed/train.csv"),
        help="Full training CSV generated by preprocessing",
    )
    parser.add_argument(
        "--tuned-train-csv",
        type=Path,
        default=Path("datasets/LSTM/processed/train_tuned.csv"),
        help="Output tuned subset CSV used for bounded training",
    )
    parser.add_argument(
        "--exe",
        type=Path,
        default=Path("build/Debug/first_gpu_program.exe"),
        help="Path to training executable",
    )
    parser.add_argument("--timeout-sec", type=float, default=4.0, help="Per-run timeout budget in seconds")
    parser.add_argument("--epochs", type=int, default=1)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--seq-len", type=int, default=16)
    parser.add_argument("--lstm-hidden", type=int, default=32)
    parser.add_argument("--lr", type=float, default=0.005)
    parser.add_argument("--optimizer", type=str, default="adam")
    parser.add_argument("--max-trials", type=int, default=12)
    parser.add_argument(
        "--min-trials",
        type=int,
        default=6,
        help="Minimum number of trials before early-stop is allowed",
    )
    parser.add_argument(
        "--report-json",
        type=Path,
        default=Path("datasets/LSTM/processed/autotune_report.json"),
        help="Summary report output",
    )
    parser.add_argument(
        "--sampling-pool-csv",
        type=Path,
        default=Path("datasets/LSTM/processed/train_tune_pool.csv"),
        help="Class-balanced sampling pool used by tuner",
    )
    parser.add_argument(
        "--sampling-pool-rows",
        type=int,
        default=50000,
        help="Target row count for sampling pool",
    )
    return parser.parse_args()


def count_data_rows(csv_path: Path) -> int:
    count = 0
    with csv_path.open("r", encoding="utf-8", newline="") as handle:
        next(handle, None)
        for _ in handle:
            count += 1
    return count


def write_subset_csv(src: Path, dst: Path, n_rows: int) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    with src.open("r", encoding="utf-8", newline="") as src_handle, dst.open(
        "w", encoding="utf-8", newline=""
    ) as dst_handle:
        reader = csv.reader(src_handle)
        writer = csv.writer(dst_handle)
        header = next(reader, None)
        if header is None:
            raise ValueError(f"CSV is empty: {src}")
        writer.writerow(header)
        written = 0
        for row in reader:
            writer.writerow(row)
            written += 1
            if written >= n_rows:
                break


def compute_class_counts(csv_path: Path) -> tuple[int, int]:
    pos = 0
    neg = 0
    with csv_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.reader(handle)
        next(reader, None)
        for row in reader:
            if not row:
                continue
            label = row[-1].strip()
            if label == "1":
                pos += 1
            elif label == "0":
                neg += 1
    return pos, neg


def build_balanced_pool(src: Path, dst: Path, target_rows: int) -> None:
    rng = random.Random(42)
    k_pos = target_rows // 2
    k_neg = target_rows - k_pos
    pos_reservoir: List[List[str]] = []
    neg_reservoir: List[List[str]] = []
    all_reservoir: List[List[str]] = []
    seen_pos = 0
    seen_neg = 0
    seen_all = 0

    with src.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.reader(handle)
        header = next(reader, None)
        if header is None:
            raise ValueError(f"CSV is empty: {src}")

        for row in reader:
            if not row:
                continue

            seen_all += 1
            if len(all_reservoir) < target_rows:
                all_reservoir.append(row)
            else:
                j_all = rng.randint(0, seen_all - 1)
                if j_all < target_rows:
                    all_reservoir[j_all] = row

            label = row[-1].strip()
            if label == "1":
                seen_pos += 1
                if len(pos_reservoir) < k_pos:
                    pos_reservoir.append(row)
                else:
                    j_pos = rng.randint(0, seen_pos - 1)
                    if j_pos < k_pos:
                        pos_reservoir[j_pos] = row
            elif label == "0":
                seen_neg += 1
                if len(neg_reservoir) < k_neg:
                    neg_reservoir.append(row)
                else:
                    j_neg = rng.randint(0, seen_neg - 1)
                    if j_neg < k_neg:
                        neg_reservoir[j_neg] = row

    merged = pos_reservoir + neg_reservoir
    if len(merged) < target_rows:
        need = target_rows - len(merged)
        merged.extend(all_reservoir[:need])

    rng.shuffle(merged)

    dst.parent.mkdir(parents=True, exist_ok=True)
    with src.open("r", encoding="utf-8", newline="") as src_handle, dst.open(
        "w", encoding="utf-8", newline=""
    ) as dst_handle:
        reader = csv.reader(src_handle)
        writer = csv.writer(dst_handle)
        header = next(reader, None)
        if header is None:
            raise ValueError(f"CSV is empty: {src}")
        writer.writerow(header)
        writer.writerows(merged[:target_rows])


def run_training(args: argparse.Namespace, dataset_path: Path, timeout_sec: float) -> tuple[bool, float, int | None, bool]:
    command = [
        str(args.exe),
        "--model",
        "lstm",
        "--dataset",
        str(dataset_path),
        "--epochs",
        str(args.epochs),
        "--batch-size",
        str(args.batch_size),
        "--print-every",
        "1",
        "--seq-len",
        str(args.seq_len),
        "--lstm-hidden",
        str(args.lstm_hidden),
        "--lr",
        str(args.lr),
        "--optimizer",
        args.optimizer,
        "--backend",
        "cpu",
    ]

    start = time.perf_counter()
    try:
        completed = subprocess.run(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            timeout=timeout_sec,
            check=False,
            cwd=Path.cwd(),
        )
        elapsed = time.perf_counter() - start
        ok = completed.returncode == 0
        return ok, elapsed, completed.returncode, False
    except subprocess.TimeoutExpired:
        elapsed = time.perf_counter() - start
        return False, elapsed, None, True


def main() -> int:
    args = parse_args()

    if not args.full_train_csv.exists():
        raise FileNotFoundError(f"Full train CSV not found: {args.full_train_csv}")
    if not args.exe.exists():
        raise FileNotFoundError(f"Executable not found: {args.exe}")
    if args.timeout_sec <= 0.0:
        raise ValueError("timeout-sec must be positive")
    if args.min_trials <= 0:
        raise ValueError("min-trials must be positive")
    if args.max_trials <= 0:
        raise ValueError("max-trials must be positive")
    if args.min_trials > args.max_trials:
        raise ValueError("min-trials must be <= max-trials")
    if args.seq_len <= 0:
        raise ValueError("seq-len must be positive")
    if args.sampling_pool_rows <= 0:
        raise ValueError("sampling-pool-rows must be positive")

    full_rows = count_data_rows(args.full_train_csv)
    effective_pool_rows = min(args.sampling_pool_rows, full_rows)
    build_balanced_pool(args.full_train_csv, args.sampling_pool_csv, effective_pool_rows)

    total_rows = count_data_rows(args.sampling_pool_csv)
    min_rows = max(args.seq_len + 1, 256)
    if total_rows < min_rows:
        raise ValueError(
            f"Not enough rows in sampling pool ({total_rows}) for seq-len={args.seq_len}; needs >= {min_rows}"
        )

    # Congestion-control style tuner:
    # - slow start: exponentially increase until first timeout/failure
    # - congestion avoidance: additive increase, multiplicative decrease (AIMD)
    mode = "slow_start"
    cwnd = min(4096, total_rows)
    ai_step = 1024
    md_factor = 0.7

    best_good_rows = 0
    best_good_time = float("inf")
    trials: List[TrialResult] = []

    for trial in range(1, args.max_trials + 1):
        cwnd = max(min_rows, min(cwnd, total_rows))
        write_subset_csv(args.sampling_pool_csv, args.tuned_train_csv, cwnd)

        ok, elapsed, return_code, timed_out = run_training(args, args.tuned_train_csv, args.timeout_sec)
        status = "ok" if ok else ("timeout" if timed_out else "error")
        trials.append(
            TrialResult(
                trial=trial,
                rows=cwnd,
                status=status,
                elapsed_sec=elapsed,
                return_code=return_code,
                timed_out=timed_out,
            )
        )
        print(
            f"trial={trial} mode={mode} rows={cwnd} status={status} elapsed={elapsed:.3f}s"
        )

        if ok:
            if cwnd > best_good_rows or (cwnd == best_good_rows and elapsed < best_good_time):
                best_good_rows = cwnd
                best_good_time = elapsed

            if mode == "slow_start":
                next_cwnd = cwnd * 2
                if next_cwnd > total_rows:
                    mode = "avoidance"
                    cwnd = total_rows
                else:
                    cwnd = next_cwnd
            else:
                cwnd = cwnd + ai_step
                ai_step = min(ai_step + 128, 8192)

        else:
            if mode == "slow_start":
                mode = "avoidance"
            cwnd = max(min_rows, int(math.floor(cwnd * md_factor)))
            ai_step = max(256, ai_step // 2)

        # Stop when we already found a good budget and window is tight.
        if mode == "avoidance" and best_good_rows > 0:
            distance = abs(cwnd - best_good_rows)
            if distance <= max(256, best_good_rows // 20) and trial >= args.min_trials:
                break

    if best_good_rows == 0:
        raise RuntimeError("No sample size finished within timeout budget")

    # Rebuild tuned dataset exactly with best rows and validate one final bounded run.
    write_subset_csv(args.sampling_pool_csv, args.tuned_train_csv, best_good_rows)
    ok, elapsed, return_code, timed_out = run_training(args, args.tuned_train_csv, args.timeout_sec)
    final_status = "ok" if ok else ("timeout" if timed_out else "error")

    tuned_pos, tuned_neg = compute_class_counts(args.tuned_train_csv)

    report = {
        "timeout_sec": args.timeout_sec,
        "max_trials": args.max_trials,
        "min_trials": args.min_trials,
        "mode": "congestion_control_aimd",
        "full_rows": full_rows,
        "sampling_pool_rows": total_rows,
        "sampling_pool_target_rows": effective_pool_rows,
        "sampling_pool_csv": str(args.sampling_pool_csv),
        "min_rows": min_rows,
        "best_good_rows": best_good_rows,
        "best_good_elapsed_sec": best_good_time,
        "final_validation": {
            "status": final_status,
            "elapsed_sec": elapsed,
            "return_code": return_code,
            "timed_out": timed_out,
        },
        "command": {
            "epochs": args.epochs,
            "batch_size": args.batch_size,
            "seq_len": args.seq_len,
            "lstm_hidden": args.lstm_hidden,
            "lr": args.lr,
            "optimizer": args.optimizer,
        },
        "tuned_train_class_balance": {
            "positives": tuned_pos,
            "negatives": tuned_neg,
            "positive_ratio": tuned_pos / max(1, tuned_pos + tuned_neg),
        },
        "trials": [asdict(t) for t in trials],
    }

    args.report_json.parent.mkdir(parents=True, exist_ok=True)
    with args.report_json.open("w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=2)

    print(f"best_good_rows={best_good_rows}")
    print(f"best_good_elapsed_sec={best_good_time:.3f}")
    print(f"final_validation_status={final_status}")
    print(f"tuned_train_csv={args.tuned_train_csv}")
    print(f"report_json={args.report_json}")

    if final_status != "ok":
        raise RuntimeError(
            "Found a candidate budget but final validation did not complete within timeout"
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
